// See https://github.com/acdlite/flux-standard-action

// Session
export const SESSION_LOAD = 'SESSION_LOAD';
export const SESSION_LOGIN = 'SESSION_LOGIN';
export const SESSION_ARGS_UPDATE = 'SESSION_ARGS_UPDATE';//to update username and token in store
export const SESSION_LOGOUT = 'SESSION_LOGOUT';

// Dashboard
export const DASHBOARD_LOAD = 'DASHBOARD_LOAD';
export const DASHBOARD_UNLOAD = 'DASHBOARD_UNLOAD';
export const DASHBOARD_LOAD_FAILURE = 'DASHBOARD_LOAD_FAILURE';

//LOGS
export const LOGS_LOAD = 'LOGS_LOAD';
export const LOGS_UNLOAD = 'LOGS_UNLOAD';
export const LOGS_LOAD_FAILURE = 'LOGS_LOAD_FAILURE';

//SYSinFO
//SYSTEMINFO SUMMARY
export const SYSSUMMARY_LOAD = 'SYSSUMMARY_LOAD';
export const SYSSUMMARY_UNLOAD = 'SYSSUMMARY_UNLOAD';
export const SYSSUMMARY_LOAD_FAILURE = 'SYSSUMMARY_LOAD_FAILURE';
//Device Inventory
export const DEVICEINVENTORY_LOAD = 'DEVICEINVENTORY_LOAD';
export const DEVICEINVENTORY_UNLOAD = 'DEVICEINVENTORY_UNLOAD';
export const DEVICEINVENTORY_LOAD_FAILURE = 'DEVICEINVENTORY_LOAD_FAILURE';


//System Network SUMMARY
export const NETWORK_LOAD = 'NETWORK_LOAD';
export const NETWORK_UNLOAD = 'NETWORK_UNLOAD';
export const NETWORK_LOAD_FAILURE = 'NETWORK_LOAD_FAILURE';
//System MEMORY SUMMARY
export const MEMORY_LOAD = 'MEMORY_LOAD';
export const MEMORY_UNLOAD = 'MEMORY_UNLOAD';
export const MEMORY_LOAD_FAILURE = 'MEMORY_LOAD_FAILURE';
//System Processor SUMMARY
export const PROCESSOR_LOAD = 'PROCESSOR_LOAD';
export const PROCESSOR_UNLOAD = 'PROCESSOR_UNLOAD';
export const PROCESSOR_LOAD_FAILURE = 'PROCESSOR_LOAD_FAILURE';


//POWER SUMMARY
export const POWERSUMMARY_LOAD = 'POWERSUMMARY_LOAD';
export const POWERSUMMARY_UNLOAD = 'POWERSUMMARY_UNLOAD';
export const POWERSUMMARY_LOAD_FAILURE = 'POWERSUMMARY_LOAD_FAILURE';

//NETWORK SUMMARY
export const NETWORKSUMMARY_LOAD = 'NETWORKSUMMARY_LOAD';
export const NETWORKSUMMARY_UNLOAD = 'NETWORKSUMMARY_UNLOAD';
export const NETWORKSUMMARY_LOAD_FAILURE = 'NETWORKSUMMARY_LOAD_FAILURE';


//NETWORK GENERAL
//export const NETWORKGENERAL_LOAD = 'NETWORKGENERAL_LOAD';
export const NETWORKGENERAL_ERROR = 'NETWORKGENERAL_ERROR';


//WIFI and LTE

export const WIFI_LOAD = 'WIFI_LOAD';
export const WIFI_UNLOAD = 'WIFI_UNLOAD';
export const WIFI_LOAD_FAILURE = 'WIFI_LOAD_FAILURE';
export const WIFICONFIGURED_LOAD = 'WIFICONFIGURED_LOAD';

export const LTE_LOAD = 'LTE_LOAD';
export const LTE_UNLOAD = 'LTE_UNLOAD';
export const LTE_LOAD_FAILURE = 'LTE_LOAD_FAILURE';

export const WIFIAP_LOAD = 'WIFIAP_LOAD';
export const WIFIAP_UNLOAD = 'WIFIAP_UNLOAD';
export const WIFIAP_LOAD_FAILURE = 'WIFIAP_LOAD_FAILURE';



//Information
export const INFORMATION_LOAD = 'INFORMATION_LOAD';
export const INFORMATION_UNLOAD = 'INFORMATION_UNLOAD';


// Tasks
export const TASKS_LOAD = 'TASKS_LOAD';
export const TASKS_UNLOAD = 'TASKS_UNLOAD';
export const TASK_LOAD = 'TASK_LOAD';
export const TASK_UNLOAD = 'TASK_UNLOAD';

// Nav
export const NAV_ACTIVATE = 'NAV_ACTIVATE';
export const NAV_ENABLE = 'NAV_ENABLE';
export const NAV_RESPONSIVE = 'NAV_RESPONSIVE';

//Firmware
export const FIRMWARE_LOAD = 'FIRMWARE_LOAD';
export const FIRMWARE_UNLOAD = 'FIRMWARE_UNLOAD';
export const FIRMWAREITEMS_LOAD = 'FIRMWAREITEMS_LOAD';
export const FIRMWARE_LOAD_FAILURE = 'FIRMWARE_LOAD_FAILURE';

//Firmware_Repo
export const REPO_LOAD = 'REPO_LOAD';
export const REPO_UNLOAD = 'REPO_UNLOAD';
export const REPO_LOAD_FAILURE = 'REPO_LOAD_FAILURE';



//Remote Console
export const REMOTE_CONSOLE_LOAD = 'REMOTE_CONSOLE_LOAD'
export const REMOTE_CONSOLE_UNLOAD = 'REMOTE_CONSOLE_UNLOAD'


//TEMPERATURE SUMMARY
export const TEMPERATURE_LOAD = 'TEMPERATURE_LOAD';
export const TEMPERATURE_UNLOAD = 'TEMPERATURE_UNLOAD';
export const TEMPERATURE_LOAD_FAILURE = 'TEMPERATURE_LOAD_FAILURE';

//System power
export const COMPUTER_RESET = 'COMPUTER_RESET';
export const SYSTEMPOWER_LOAD = 'SYSTEMPOWER_LOAD';
export const SYSTEMPOWER_LOAD_FAILURE = 'SYSTEMPOWER_LOAD_FAILURE';
export const SYSTEMPOWER_UNLOAD = 'SYSTEMPOWER_UNLOAD';


//SECURITY

//LOGINSECURITYBANNER
export const LOGINSECURITYBANNER_LOAD = 'LOGINSECURITYBANNER_LOAD';
export const LOGINSECURITYBANNER_UNLOAD = 'LOGINSECURITYBANNER_UNLOAD';
export const LOGINSECURITYBANNER_LOAD_FAILURE = 'LOGINSECURITYBANNER_LOAD_FAILURE';

//ACCESSSETTINGS
export const ACCESSSETTINGS_LOAD = 'ACCESSSETTINGS_LOAD';
export const ACCESSSETTINGS_UNLOAD = 'ACCESSSETTINGS_UNLOAD';
export const ACCESSSETTINGS_LOAD_FAILURE = 'ACCESSSETTINGS_LOAD_FAILURE';

//ADMINISTATION

//BOOTORDER
export const BOOTORDER_LOAD = 'BOOTORDER_LOAD';
export const BOOTORDER_UNLOAD = 'BOOTORDER_UNLOAD';
export const BOOTORDER_LOAD_FAILURE = 'BOOTORDER_LOAD_FAILURE';

//USER ADMINISTRATION
export const USERADMIN_LOAD = 'USERADMIN_LOAD';
export const USERADMIN_UNLOAD = 'USERADMIN_UNLOAD';
export const USERADMIN_LOAD_FAILURE = 'USERADMIN_LOAD_FAILURE';
export const USERADMINEDIT_LOAD = 'USERADMINEDIT_LOAD';

//SSH
export const SSH_LOAD = 'SSH_LOAD';
export const SSH_LOAD_FAILURE = 'SSH_LOAD_FAILURE';
export const SSH_UNLOAD = 'SSH_UNLOAD';

//OPTIONAL CARDS
export const OPTIONALCARDS_LOAD = 'OPTIONALCARDS_LOAD';
export const OPTIONALCARDS_UNLOAD = 'OPTIONALCARDS_UNLOAD';
export const OPTIONALCARDS_LOAD_FAILURE = 'OPTIONALCARDS_LOAD_FAILURE';


export const BACKUP_AND_RESTORE_LOAD = 'BACKUP_AND_RESTORE_LOAD';
export const BACKUP_AND_RESTORE_UNLOAD = 'BACKUP_AND_RESTORE_UNLOAD';
export const BACKUP = 'BACKUP';
export const RESTORE = 'RESTORE';
export const FACTORY_DEFAULTS = 'FACTORY_DEFAULTS';

export const KILL_SYSTEM = 'KILL_SYSTEM';
export const KILL_SYSTEM_UNLOAD = 'KILL_SYSTEM_UNLOAD';
export const KILL_SYSTEM_LOAD = 'KILL_SYSTEM_LOAD';

export const CERTIFICATE_LOAD = 'CERTIFICATE_LOAD';
export const CERTIFICATE_UNLOAD = 'CERTIFICATE_UNLOAD';
export const CERTIFICATE_LOAD_FAILURE = 'CERTIFICATE_LOAD_FAILURE';
export const CSR_CERTIFICATE_LOAD = 'CSR_CERTIFICATE_LOAD';

export const SECURE_ERASE_SYSTEM = 'SECURE_ERASE_SYSTEM';
export const SECURE_ERASE_SYSTEM_UNLOAD ='SECURE_ERASE_SYSTEM_UNLOAD';
export const SECURE_ERASE_SYSTEM_LOAD = 'SECURE_ERASE_SYSTEM_LOAD';

//LOCK
export const LOCKED_LOAD = 'LOCKED_LOAD';


//Session list
export const SESSIONLIST_LOAD = 'SESSIONLIST_LOAD';
export const SESSIONLIST_UNLOAD = 'SESSIONLIST_UNLOAD';
export const SESSIONLIST_FAILURE = 'SESSIONLIST_FAILURE';